# Generated by Django 4.2.1 on 2023-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('mfj', 'Married Filing Jointly'), ('mfs', 'Married Filing Separately'), ('hh', 'Head of Household'), ('qw', 'Qualifying Widow')], default='mfj', max_length=32)),
                ('deduction', models.IntegerField()),
            ],
        ),
    ]
