# Generated by Django 4.2.1 on 2023-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('ordinary', 'Ordinary Income'), ('capital_gains', 'Capital Gaines')], default='ordinary', max_length=32)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('mfj', 'Married Filing Jointly'), ('mfs', 'Married Filing Separately'), ('hh', 'Head of Household'), ('qw', 'Qualifying Widow')], default='mfj', max_length=32)),
                ('bracket_order', models.IntegerField()),
                ('lower_bound', models.DecimalField(decimal_places=3, max_digits=20)),
                ('upper_bound', models.DecimalField(decimal_places=3, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
